### ISSUE TITLE
Integration is not loading

### ISSUE THREAD

**Issue by dengi76** [malinovsku/ha-keenetic_api#18]
After updating to 2025.9.0, the integration stopped loading

**Comment by dengi76** [comment]
The logs are as follows:

Регистратор: homeassistant.setup
Источник: setup.py:343
Зафиксировано первый раз: 08:15:44 (1 случай)
Зафиксировано последний раз: 08:15:44

Setup failed for custom integration 'keenetic_api': Unable to import component: cannot import name 'json_loads' from 'homeassistant.helpers.json' (/usr/src/homeassistant/homeassistant/helpers/json.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/keenetic_api/__init__.py", line 30, in <module>
    from homeassistant.helpers.json import json_loads
ImportError: cannot import name 'json_loads' from 'homeassistant.helpers.json' (/usr/src/homeassistant/homeassistant/helpers/json.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/keenetic_api/__init__.py", line 30, in <module>
    from homeassistant.helpers.json import json_loads
ImportError: cannot import name 'json_loads' from 'homeassistant.helpers.json' (/usr/src/homeassistant/homeassistant/helpers/json.py)

**Comment by Betweener1993** [comment]
Такая же проблема сразу после установки обновления HA Core 2025.9.0.

**Comment by UltrasSlim** [comment]
Я решил проблему установкой beta версии

**Comment by Betweener1993** [comment]
> Я решил проблему установкой beta версии

А как её установить/перейти на неё?

**Comment by UltrasSlim** [comment]
> > Я решил проблему установкой beta версии
> 
> А как её установить/перейти на неё?

В HACS ее найдите, потом в правом верхнем углу троеточие и "Скачать повторно". И там уже из списка выберете beta-версию

**Comment by Betweener1993** [comment]
> > > Я решил проблему установкой beta версии
> > 
> > 
> > А как её установить/перейти на неё?
> 
> В HACS ее найдите, потом в правом верхнем углу троеточие и "Скачать повторно". И там уже из списка выберете beta-версию

Супер, помогло! Спасибо большое!
Пока вижу это как решение проблемы. В дальнейшем, полагаю, автор продолжит работу над обновлениями, ведь это же бета-версия.
